[package]
name = "cons-util"
version = "0.1.0"
edition = "2021"

[features]
js = []

[dependencies]
chrono = "0"
cons-util-derive = { path = "C:/Users/Garnet3106/Desktop/Media/Docs/Repos/cons-util-derive" }
regex = "1"
same-file = "1"
wasm-bindgen = "0.2"
